// <auto-generated />
using System;
using HacatonMax.University.Events.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HacatonMax.University.Events.Infrastructure.Migrations
{
    [DbContext(typeof(UniversityEventsDbContext))]
    [Migration("20251113013235_AddEventLocationAndRegistrations")]
    partial class AddEventLocationAndRegistrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("university-events")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HacatonMax.University.Events.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tags", "university-events");
                });

            modelBuilder.Entity("HacatonMax.University.Events.Domain.UniversityEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_datetime");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<long?>("ParticipantsLimit")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_datetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("university_events", "university-events");
                });

            modelBuilder.Entity("HacatonMax.University.Events.Domain.UniversityEventRegistration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("UniversityEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("university_event_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UniversityEventId", "UserId")
                        .IsUnique();

                    b.ToTable("university_event_registrations", "university-events");
                });

            modelBuilder.Entity("university_events_tags", b =>
                {
                    b.Property<long>("university_event_id")
                        .HasColumnType("bigint");

                    b.Property<Guid>("tag_id")
                        .HasColumnType("uuid");

                    b.HasKey("university_event_id", "tag_id");

                    b.HasIndex("tag_id");

                    b.ToTable("university_events_tags", "university-events");
                });

            modelBuilder.Entity("HacatonMax.University.Events.Domain.UniversityEventRegistration", b =>
                {
                    b.HasOne("HacatonMax.University.Events.Domain.UniversityEvent", "UniversityEvent")
                        .WithMany("Registrations")
                        .HasForeignKey("UniversityEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UniversityEvent");
                });

            modelBuilder.Entity("university_events_tags", b =>
                {
                    b.HasOne("HacatonMax.University.Events.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HacatonMax.University.Events.Domain.UniversityEvent", null)
                        .WithMany()
                        .HasForeignKey("university_event_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HacatonMax.University.Events.Domain.UniversityEvent", b =>
                {
                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
