// <auto-generated />
using System;
using HacatonMax.University.Library.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HacatonMax.University.Library.Infrastructure.Migrations
{
    [DbContext(typeof(UniversityLibraryDbContext))]
    [Migration("20251111231628_AddedAuthorPart2")]
    partial class AddedAuthorPart2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("university-library")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HacatonMax.University.Library.Domain.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<long>("Count")
                        .HasColumnType("bigint")
                        .HasColumnName("count");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("TakeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("take_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("books", "university-library");
                });

            modelBuilder.Entity("HacatonMax.University.Library.Domain.ReservationBook", b =>
                {
                    b.Property<long>("ReservationOwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("reservation_owner_id");

                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<int>("CountExtendReservation")
                        .HasColumnType("integer")
                        .HasColumnName("count_extend_reservation");

                    b.Property<DateTimeOffset>("EndReservationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_reservation_date");

                    b.HasKey("ReservationOwnerId", "BookId");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.ToTable("reservation_books", "university-library");
                });

            modelBuilder.Entity("HacatonMax.University.Library.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tags", "university-library");
                });

            modelBuilder.Entity("HacatonMax.University.Library.Domain.UserFavoriteBook", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("user_favorite_books", "university-library");
                });

            modelBuilder.Entity("university_books_tags", b =>
                {
                    b.Property<long>("university_book_id")
                        .HasColumnType("bigint");

                    b.Property<Guid>("tag_id")
                        .HasColumnType("uuid");

                    b.HasKey("university_book_id", "tag_id");

                    b.HasIndex("tag_id");

                    b.ToTable("university_books_tags", "university-library");
                });

            modelBuilder.Entity("HacatonMax.University.Library.Domain.ReservationBook", b =>
                {
                    b.HasOne("HacatonMax.University.Library.Domain.Book", "Book")
                        .WithOne()
                        .HasForeignKey("HacatonMax.University.Library.Domain.ReservationBook", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("HacatonMax.University.Library.Domain.UserFavoriteBook", b =>
                {
                    b.HasOne("HacatonMax.University.Library.Domain.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("university_books_tags", b =>
                {
                    b.HasOne("HacatonMax.University.Library.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HacatonMax.University.Library.Domain.Book", null)
                        .WithMany()
                        .HasForeignKey("university_book_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
