// <auto-generated />
using HacatonMax.Admin.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HacatonMax.Admin.Infrastructure.Migration
{
    [DbContext(typeof(AdminDbContext))]
    partial class AdminDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("admin")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HacatonMax.Admin.Domain.University", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_name");

                    b.HasKey("Id");

                    b.ToTable("universities", "admin");
                });

            modelBuilder.Entity("HacatonMax.Admin.Domain.UserInUniversity", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("UniversityId")
                        .HasColumnType("bigint")
                        .HasColumnName("university_id");

                    b.Property<string>("ApproveStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("approve_status");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("university_name");

                    b.HasKey("UserId", "UniversityId");

                    b.HasIndex("UserId");

                    b.ToTable("students_in_universities", "admin");
                });
#pragma warning restore 612, 618
        }
    }
}
