// <auto-generated />
using System;
using HacatonMax.University.Deadlines.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HacatonMax.University.Deadlines.Infrastructure.Migrations
{
    [DbContext(typeof(DeadlinesDbContext))]
    partial class DeadlinesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("deadlines")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HacatonMax.University.Deadlines.Domain.Deadline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessScope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_scope");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("creator_user_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DescriptionHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_html");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<long>("LastEditorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_editor_user_id");

                    b.Property<DateTimeOffset?>("LastNotificationAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_notification_at");

                    b.Property<long?>("ScheduleEntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_entry_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleEntryId")
                        .HasFilter("schedule_entry_id IS NOT NULL");

                    b.HasIndex("TenantId", "GroupId");

                    b.ToTable("deadlines", "deadlines");
                });

            modelBuilder.Entity("HacatonMax.University.Deadlines.Domain.DeadlineCompletion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<long>("DeadlineId")
                        .HasColumnType("bigint")
                        .HasColumnName("deadline_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DeadlineId", "UserId")
                        .IsUnique();

                    b.HasIndex("TenantId", "UserId");

                    b.ToTable("deadline_completions", "deadlines");
                });

            modelBuilder.Entity("HacatonMax.University.Deadlines.Domain.DeadlineReminder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DeadlineId")
                        .HasColumnType("bigint")
                        .HasColumnName("deadline_id");

                    b.Property<string>("Offset")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("offset");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id");

                    b.HasIndex("DeadlineId", "Offset")
                        .IsUnique();

                    b.ToTable("deadline_reminders", "deadlines");
                });

            modelBuilder.Entity("HacatonMax.University.Deadlines.Domain.DeadlineCompletion", b =>
                {
                    b.HasOne("HacatonMax.University.Deadlines.Domain.Deadline", "Deadline")
                        .WithMany("Completions")
                        .HasForeignKey("DeadlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deadline");
                });

            modelBuilder.Entity("HacatonMax.University.Deadlines.Domain.DeadlineReminder", b =>
                {
                    b.HasOne("HacatonMax.University.Deadlines.Domain.Deadline", "Deadline")
                        .WithMany("Reminders")
                        .HasForeignKey("DeadlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deadline");
                });

            modelBuilder.Entity("HacatonMax.University.Deadlines.Domain.Deadline", b =>
                {
                    b.Navigation("Completions");

                    b.Navigation("Reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
