// <auto-generated />
using System;
using HacatonMax.University.StudentsProject.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HacatonMax.University.StudentsProject.Infrastructure.Migrations;

[DbContext(typeof(StudentProjectsDbContext))]
[Migration("20251112130000_AddProjectParticipants")]
partial class AddProjectParticipants
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("students-projects")
            .HasAnnotation("ProductVersion", "9.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("HacatonMax.University.StudentsProject.Domain.Skill", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("name");

                b.HasKey("Id");

                b.ToTable("skills", "students-projects");
            });

        modelBuilder.Entity("HacatonMax.University.StudentsProject.Domain.SkillStudentProject", b =>
            {
                b.Property<Guid>("SkillId")
                    .HasColumnType("uuid");

                b.Property<Guid>("StudentProjectId")
                    .HasColumnType("uuid");

                b.HasKey("SkillId", "StudentProjectId");

                b.HasIndex("StudentProjectId");

                b.ToTable("skill_student_projects", "students-projects");
            });

        modelBuilder.Entity("HacatonMax.University.StudentsProject.Domain.StudentProject", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("description");

                b.Property<long>("CreatorId")
                    .HasColumnType("bigint")
                    .HasColumnName("creator_id");

                b.Property<long?>("EventId")
                    .HasColumnType("bigint")
                    .HasColumnName("event_id");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("title");

                b.HasKey("Id");

                b.ToTable("student_projects", "students-projects");
            });

        modelBuilder.Entity("HacatonMax.University.StudentsProject.Domain.StudentProjectParticipant", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<bool>("IsCreator")
                    .HasColumnType("boolean")
                    .HasColumnName("is_creator");

                b.Property<int>("Status")
                    .HasColumnType("integer")
                    .HasColumnName("status");

                b.Property<Guid>("StudentProjectId")
                    .HasColumnType("uuid")
                    .HasColumnName("student_project_id");

                b.Property<long>("UserId")
                    .HasColumnType("bigint")
                    .HasColumnName("user_id");

                b.HasKey("Id");

                b.HasIndex("StudentProjectId");

                b.HasIndex("StudentProjectId", "UserId")
                    .IsUnique();

                b.ToTable("student_project_participants", "students-projects");
            });

        modelBuilder.Entity("HacatonMax.University.StudentsProject.Domain.StudentProjectParticipantRole", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<Guid>("ParticipantId")
                    .HasColumnType("uuid")
                    .HasColumnName("participant_id");

                b.Property<Guid>("TeamRoleId")
                    .HasColumnType("uuid")
                    .HasColumnName("team_role_id");

                b.HasKey("Id");

                b.HasIndex("ParticipantId");

                b.HasIndex("TeamRoleId");

                b.HasIndex("ParticipantId", "TeamRoleId")
                    .IsUnique();

                b.ToTable("student_project_participant_roles", "students-projects");
            });

        modelBuilder.Entity("HacatonMax.University.StudentsProject.Domain.TeamRole", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Description")
                    .HasColumnType("text")
                    .HasColumnName("description");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("name");

                b.HasKey("Id");

                b.ToTable("team_roles", "students-projects");
            });

        modelBuilder.Entity("HacatonMax.University.StudentsProject.Domain.SkillStudentProject", b =>
            {
                b.HasOne("HacatonMax.University.StudentsProject.Domain.Skill", "Skill")
                    .WithMany()
                    .HasForeignKey("SkillId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HacatonMax.University.StudentsProject.Domain.StudentProject", "StudentProject")
                    .WithMany()
                    .HasForeignKey("StudentProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Skill");

                b.Navigation("StudentProject");
            });

        modelBuilder.Entity("HacatonMax.University.StudentsProject.Domain.StudentProjectParticipant", b =>
            {
                b.HasIndex("StudentProjectId");

                b.HasIndex("StudentProjectId", "UserId")
                    .IsUnique();

                b.HasOne("HacatonMax.University.StudentsProject.Domain.StudentProject", "StudentProject")
                    .WithMany("Participants")
                    .HasForeignKey("StudentProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("StudentProject");
            });

        modelBuilder.Entity("HacatonMax.University.StudentsProject.Domain.StudentProjectParticipantRole", b =>
            {
                b.HasIndex("ParticipantId");

                b.HasIndex("TeamRoleId");

                b.HasOne("HacatonMax.University.StudentsProject.Domain.StudentProjectParticipant", "Participant")
                    .WithMany("ParticipantRoles")
                    .HasForeignKey("ParticipantId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HacatonMax.University.StudentsProject.Domain.TeamRole", "TeamRole")
                    .WithMany()
                    .HasForeignKey("TeamRoleId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Participant");

                b.Navigation("TeamRole");
            });

        modelBuilder.Entity("HacatonMax.University.StudentsProject.Domain.StudentProject", b =>
            {
                b.Navigation("Participants");
            });
#pragma warning restore 612, 618
    }
}

