// <auto-generated />
using System;
using HacatonMax.University.StudentsProject.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HacatonMax.University.StudentsProject.Infrastructure.Migrations
{
    [DbContext(typeof(StudentProjectsDbContext))]
    [Migration("20251112120000_AddStudentProjectEventLink")]
    partial class AddStudentProjectEventLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("students-projects")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HacatonMax.University.StudentsProject.Domain.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("skills", "students-projects");
                });

            modelBuilder.Entity("HacatonMax.University.StudentsProject.Domain.SkillStudentProject", b =>
                {
                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("SkillId", "StudentProjectId");

                    b.HasIndex("StudentProjectId");

                    b.ToTable("skill_student_projects", "students-projects");
                });

            modelBuilder.Entity("HacatonMax.University.StudentsProject.Domain.StudentProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long?>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("student_projects", "students-projects");
                });

            modelBuilder.Entity("HacatonMax.University.StudentsProject.Domain.SkillStudentProject", b =>
                {
                    b.HasOne("HacatonMax.University.StudentsProject.Domain.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HacatonMax.University.StudentsProject.Domain.StudentProject", "StudentProject")
                        .WithMany()
                        .HasForeignKey("StudentProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("StudentProject");
                });
#pragma warning restore 612, 618
        }
    }
}

